version: "3.9"
services:
  app:
    build: ./
    ports:
      - "5500:5500"
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/CloudService
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: mysql
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_LIQUIBASE_URL: jdbc:mysql://database:3306/CloudService
      SPRING_LIQUIBASE_USER: root
      SPRING_LIQUIBASE_PASSWORD: mysql

  database:
    image: mysql
    container_name: 'CloudService-db'
    volumes:
      - /mysql_data:/var/lib/mysql
    environment:
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: mysql
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: CloudService
    ports:
      - "3306:3306"